spring.application.name=uvalert

# KMA Common
kma.service-key=${KMA_SERVICE_KEY}

# Living Weather Index API
kma.living-weather.base-url=http://apis.data.go.kr/1360000/LivingWthrIdxServiceV5
kma.living-weather.uv-path=/getUVIdxV5
kma.living-weather.air-stagnation-path=/getAirDiffusionIdxV5

# Short Forecast API
kma.short-forecast.base-url=http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
kma.short-forecast.path=/getVilageFcst