spring.application.name=uvmanager
spring.profiles.default=local

spring.jpa.open-in-view=false

server.port=8080

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=10m

# Living Weather Index API
kma.living-weather.base-url=http://apis.data.go.kr/1360000/LivingWthrIdxServiceV5
kma.living-weather.uv-path=/getUVIdxV5

# Short Forecast API
kma.short-forecast.base-url=http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
kma.short-forecast.path=/getVilageFcst