spring.datasource.url=jdbc:postgresql://localhost:5432/uvmanger
spring.datasource.username=uvmanger
spring.datasource.password=uvmanger

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

kma.service-key=${KMA_SERVICE_KEY}